dist: xenial

language: java
install: ant deps
install: true

matrix:
  include:
  - jdk: openjdk10

script:
  - git config --global push.default simple
  - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - ant clean 
  - ant compile
  - ant jar
  - ant run
